### ISSUE TITLE
Can you share the npy file? Thank you very much!

### ISSUE THREAD

**Issue by c1a1o1** [tailongnguyen/Satellite-Image-Forgery-Detection-and-Localization#2]
Can you share the npy file? Thank you very much!

**Comment by tailongnguyen** [comment]
@c1a1o1 You can get the dataset [here](https://drive.google.com/file/d/121PpxwFCAMuPHLliD4aS08db8YtK6o8U/view?usp=sharing). These are satellite images I crawled from Goolge few months ago.

**Comment by c1a1o1** [comment]
Thank you very much! It is a great work!

**Comment by Sorkanius** [comment]
Can you guys tell me how to make the npy file from the dataset you have provided?

Thank you so much. The work is amazing.

**Comment by tailongnguyen** [comment]
@Sorkanius Just read the images using any image processing package like PIL, opencv, scipy, skimage, ... and convert them to numpy array, put them in a single numpy array before saving it using `np.save(<filename>, <array_to_save>)`
